### ISSUE TITLE
The bot should send an error when it cannot DM an user

### ISSUE THREAD

**Issue by RedsTom** [RedsTom/TicketTools#10]
Currently : says that tickets is already opened

Should : Say that is unable to DM

**Comment by AntoineJT** [comment]
@RedsTom Multiples comments on your message:
- "actually" is a false friend, it means "in fact": the word you were searching for is "now"
- your description of the bug is not sufficient: it's not precise enough and it includes no steps to reproduce the bug (here it's not a big deal because that's obvious, but that's not a correct bug report)

⚠️ Following testing, the bug is not exactly what you explain.

The bug is that, if the bot can't DM you, it tries anyway and consider that you have received the message allowing to open the ticket.
While you didn't confirm the opening of the ticket, the bot considers that a ticket is already opened with you.

🚨 This bug is actually 2 bugs in one:
- the bot ignores the fact that it can DM you or not, and considers you have received the message
- when the bot considers you have received the message allowing to open a ticket, it considers that a ticket has been opened with you, while it should just prevent sending a new message when doing a !new
